version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.6

    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-{{checksum "mix.lock"}}
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix test
      - run: mix credo --strict
      - run: mix dialyzer --halt-exit-status
      - run: mix coveralls.post --sha $(git rev-parse HEAD) --branch $(git rev-parse --abbrev-ref HEAD)
      - save_cache:
          key: build-{{checksum "mix.lock"}}
          paths:
            - deps
            - _build
