version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.5

    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-{{checksum "mix.lock"}}
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix test
      - run: mix credo --strict
      - run: mix dogma
      - save_cache:
          key: build-{{checksum "mix.lock"}}
          paths:
            - deps
            - _build
